###
POST 127.0.0.1:5000/api/user/login
Content-Type: application/json

{
    "email": "data@home.com",
    "password": "admin"
}

####
GET 127.0.0.1:5000/api/server/list


###
GET 127.0.0.1:5000/api/channel/server/3


###
POST 127.0.0.1:5000/api/message/add
Content-Type: application/json

{
  "mensajes": "Tiempo de prueba",
  "servidor_id": 3,
  "canal_id": 3,
  "autor_id": 1
}




###
#mensaje update
PUT 127.0.0.1:5000/api/message/update/7
Content-Type: application/json

{
  "mensajes": "Los tiempos cambian"
}

###
#mensaje delete
DELETE 127.0.0.1:5000/api/message/delete/6




###
#MENSAJE BY ID
GET 127.0.0.1:5000/api/message/7


###
# get mensajes
GET 127.0.0.1:5000/api/message/1


###
POST 127.0.0.1:5000/api/server/add
Content-Type: application/json

{
  "nombre_servidor": "Un servidor de prueba",
  "descripcion": "Un servidor de prueba",
  "autor_id": 1
}


###

POST 127.0.0.1:5000/api/channel/add
Content-Type: application/json

{
    "nombre_canal": "Un canal de prueba",
    "descripcion": "Un canal de prueba",
    "servidor_id": 3,
    "autor_id": 1
}

###
GET 127.0.0.1:5000/api/channel/list


###
POST 127.0.0.1:5000/api/user/add
Content-Type: application/json

{
    "nombre": "Pablito",
    "password": "pablo",
     "email": "pablo_c@gmail.com",
    "nick": "pintor"
}

###
POST 127.0.0.1:5000/api/user/login
Content-Type: application/json

{
  "email": "pintor@gmail.com",
  "password": "pintor"
}


###
GET 127.0.0.1:5000/api/server/user/2/list



###

POST 127.0.0.1:5000/api/server/add
Content-Type: application/json

{
  "nombre_servidor": "Nuevo Servidor",
  "descripcion": "Add user on server auto?",
  "autor_id": 2
}