POST 127.0.0.1:5000/api/user/login
Content-Type: application/json

{
  "email": "data@home.com",
  "password": "admin"
}

####
GET 127.0.0.1:5000/api/server/list


###
GET 127.0.0.1:5000/api/channel/server/3


###
POST 127.0.0.1:5000/api/message/add
Content-Type: application/json

{
  "mensajes": "Tiempo de prueba",
  "servidor_id": 3,
  "canal_id": 3,
  "autor_id": 1
}


###
GET 127.0.0.1:5000/api/message?id_channel=3


###
#mensaje update
PUT 127.0.0.1:5000/api/message/update/7
Content-Type: application/json

{
  "mensajes": "Los tiempos cambian"
}

###
#mensaje delete
DELETE 127.0.0.1:5000/api/message/delete/6




###
#MENSAJE BY ID
GET 127.0.0.1:5000/api/message/7


###

#CREATE USER
POST 127.0.0.1:5000/api/user/add
Content-Type: application/json

{
  "nick": "Elvio",
  "nombre": "Max",
  "apellido": "Williams",
  "email": "williams@gmail.com",
  "password": "P@ssw0rd3"
}

###
# user by id
GET 127.0.0.1:5000/api/user/2


###
# login
POST 127.0.0.1:5000/api/user/login
Content-Type: application/json

{
  "email": "luisito@gmail.com",
  "password": "administrador"
}


###
# get users
GET 127.0.0.1:5000/api/user/list



###
# UPDATE USER
PUT 127.0.0.1:5000/api/user/update/7
Content-Type: application/json

{
  "nick": "Javi",
  "nombre": "Javier",
  "apellido": "Hermosilla",
  "avatar": ""
}


###
# DELETE USER
PUT 127.0.0.1:5000/api/user/delete/1



###

#server list

GET 127.0.0.1:5000/api/server/list


###
#server disable estado = 0
GET 127.0.0.1:5000/api/server/disable


###
#server by id
GET 127.0.0.1:5000/api/server/9



###

#server create
POST 127.0.0.1:5000/api/server/add
Content-Type: application/json

{
  "nombre_servidor": "Pruebas de Errores",
  "descripcion": "Servidor de prueba con excpetions y errores",
  "autor_id": 112
}


###
#server update
PUT 127.0.0.1:5000/api/server/update/10
Content-Type: application/json

{
  "nombre_servidor": "Prueba Add",
  "descripcion": "Servidor de prueba con excpetions"
}


###

#server delete
PUT 127.0.0.1:5000/api/server/delete/9


###
# user into server

POST 127.0.0.1:5000/api/server/11/add
Content-Type: application/json

{
  "id_server": 43
}